CREATE DATABASE IF NOT EXISTS burgers_db;
USE burgers_db;

CREATE TABLE IF NOT EXISTS burgers(
id int NOT NULL AUTO_INCREMENT,
burgerName varchar(255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
PRIMARY KEY (id)
);